export const ScreenName = {
    startScreen: "StartScreen",
    splashScreen: "SplashScreen",
    login: "Login",
    forgetPassword: "ForgetPassword",
    changePassword: "ChangePassword",
    verifyPassword: "VerifyPassword",
    register: "Register",
    profile: "Profile",
    setting: "Setting",
    theme: "Theme",
    courseDetail: "CourseDetail",
    authorDetail: "AuthorDetail",
    pathDetail: "PathDetail",
    contentsTab: "ContentsTab",
    transcriptTab: "TranscriptTab",
    mainTab: "MainTab",
    homeTabNavigation: "HomeTabNavigation",
    homeTab: "HomeTab",
    downloadTabNavigation: "DownloadTabNavigation",
    downloadTab: "DownloadTab",
    browseTabNavigation: "BrowseTabNavigation",
    browseTab: "BrowseTab",
    searchTab: "SearchTab",
    searchResults: "SearchResults",
    searchResultsTabNavigation: "SearchResultsTabNavigation",
    searchAllTab: "SearchAllTab",
    searchCoursesTab: "SearchCoursesTab",
    searchPathsTab: "SearchPathsTab",
    searchAuthorsTab: "SearchAuthorsTab"
}

export const ScreenTitle = {
    login: "Sign In",
    forgetPassword: "Forget Password",
    changePassword: "Change Password",
    verifyPassword: "Verify Password",
    register: "Register",
    profile: "Profile",
    setting: "Setting",
    theme: "Theme",
    courseDetail: "Course Detail",
    authorDetail: "Author",
    pathDetail: "Path",
    contentsTab: "Contents",
    transcriptTab: "Transcript",
    homeTab: "Home",
    downloadTab: "Download",
    browseTab: "Browse",
    searchTab: "Search",
    searchAllTab: "All",
    searchCoursesTab: "Courses",
    searchPathsTab: "Paths",
    searchAuthorsTab: "Authors"
}

export const Colors = {
    transparent: "transparent",
    black: "black",
    dark: "#222222",
    white: "white",
    light: "#eeeeee",
    ghostWhite: "ghostwhite",
    boldGrey: "#383838",
    dimGrey: "dimgrey",
    darkGrey: "darkgrey",
    gainsboro: "gainsboro",
    dodgerBlue: "dodgerblue",
    red: "red",
    green: "green"
};